### PR TITLE
chore: release

### PR DESCRIPTION
**Pull request by ruisaraiva19**

### CODE REVIEW

**Comment by ruisaraiva19** [comment]
@tjallingt can you please approve this PR to proceed with the release. 🙂

**Comment by ruisaraiva19** [comment]
@tjallingt can you please approve this PR to proceed with the release. 🙂

**Comment by ruisaraiva19** [comment]
@tjallingt can you approve this PR to proceed with the release? 🙂

**Review by tjallingt — DISMISSED** [review]

**Comment by tjallingt** [comment]
Oh whoops, I broke this by merging https://github.com/tjallingt/react-youtube/pull/239
Probably should have merged this one first... We can do a temporary revert or maybe you can fix this branch?

**Comment by ruisaraiva19** [comment]
> Oh whoops, I broke this by merging #239 I think Maybe I should have merged this one first.

Don't worry, I'll revert the merge.

**Comment by tjallingt** [comment]
> You did a commit and merge instead of squash & merge 👀. When merging to canary we must use squash & merge and on the release PR (merging to master) we do commit and merge.

Github "helpfully" remembering how I merged a previous branch. My bad, thanks for fixing it.

**Comment by ruisaraiva19** [comment]
@tjallingt good to go this PR.

**Review by tjallingt — APPROVED** [review]

**Comment by tjallingt** [comment]
🎉 
Great work @ruisaraiva19

**Pull request merged**
