### PR TITLE
Version 7.11.0

### PR DESCRIPTION
**Pull request by tjallingt**

### CODE REVIEW

**Comment by ruisaraiva19** [comment]
@tjallingt I can fix the conflicts!

**Comment by ruisaraiva19** [comment]
@tjallingt Can you fix the merge conflicts?

**Comment by tjallingt** [comment]
@ruisaraiva19 thanks! Its quite late already (assuming utc+2) don't forget to take a break

**Comment by tjallingt** [comment]
Can't fix conflicts at this time :s
Can lift push restictions on canary

**Comment by ruisaraiva19** [comment]
> Can't fix conflicts at this time :s
> Can lift push restictions on canary

Ok, thanks.

**Comment by ruisaraiva19** [comment]
@tjallingt there are a couple of checks that do not exist anymore and are blocking the merge.

checks

**Comment by tjallingt** [comment]
Yea i noticed, not sure how to get rid of those.
I'll look into it tomorrow!

**Pull request merged**
