### PR TITLE
feat: make example work with CodeSandbox

### PR DESCRIPTION
**Pull request by tjallingt**
Builds on #238 (and is the reason I made that PR)

This PR adds ` "sandboxes": ["/example"]` to the codesandbox ci config and structures our example in the same way as the parcel template (with the hope that codesandbox picks up on that and automatically builds the example correctly).

There are two downsides to this structure:
- You need to link the dist folder to see the local changes in the example:
  ```sh
  yarn compile
  cp package.json /dist
  cd ./dist
  yarn link
  cd ../example
  yarn link react-youtube
  ```
- parcel doesn't rebuild when you rebuild react-youtube (since it is linked as a dependency)

These are actually kind of annoying so if anyone has a fix i'd love to hear it!

@compuives?

### CODE REVIEW

**Comment by CompuIves** [comment]
Hmm, this is a good case. I wish we would be able to even run the library in CodeSandbox mid-development, so you can test intermediate changes too... Right now I'm not sure if there is a better solution, I found `link` always to be suboptimal, since it doesn't actually update after changes.

**Comment by tjallingt** [comment]
Yea link is awkward in general.

But its especially annoying since we use react testing library so linking the lib naively will cause react to be bundled twice (and cause hook errors)

**Comment by ruisaraiva19** [comment]
@tjallingt I'm thinking of moving the `example` folder into the `src` folder and renaming it to something like `demo`. This `demo` folder would continue to be used as the development playground.

For CodeSandbox, we can create an `examples` folder on the root of the repo and have a couple of examples there, a basic one and another with TypeScript.
These two examples are the ones we would connect to CodeSandbox through the `.codesandbox/ci.json` config `"sandboxes": ["/examples/basic", "/examples/basic-typescript"]`.

This way we separate the test and development environments and don't have to deal with `yarn link` stuff.

What do you think of this approach? 🤗

**Comment by tjallingt** [comment]
Yea sounds good, linking stuff locally is always a bit of a pain so avoiding that seems worth it to me. If we could use the codesandbox examples for development that would be the nicest but its probably needlessly tricky to set that up.

**Comment by ruisaraiva19** [comment]
> Yea sounds good, linking stuff locally is always a bit of a pain so avoiding that seems worth it to me. If we could use the codesandbox examples for development that would be the nicest but its probably needlessly tricky to set that up.

@tjallingt I have another idea.

We can convert the repo into a monorepo and use [Yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) for example.

And to help us with the development, test, and build pipelines we can use [Turborepo](https://turborepo.org/) on top of Yarn workspaces.

With this approach, we can use an `example` workspace for both development and codesandbox as well.

Let me know your thoughts on this.

**Comment by tjallingt** [comment]
Mhhh not sure I've seen many other projects with such a setup. Seems fine to me if it works.

It surprises me codesandbox doesn't support `"react-youtube": "link:../src"` or something to make this work.

**Comment by ruisaraiva19** [comment]
@tjallingt I pushed a commit with the monorepo conversion.

Everything is working as expected!

Please take a look and let me know if you have any questions.

**Comment by tjallingt** [comment]
Looks good to me, all changes make sense so LGTM!

**Pull request merged**
