### PR TITLE
fix(engines): support node versions ^10.13 and 12.x

### LINKED ISSUE #223: Node version incompatibility
Is it possible to support node versions greater than 12.x.x?

### PR DESCRIPTION
**Pull request by ruisaraiva19**
fix #223

### CODE REVIEW

**Comment by tjallingt** [comment]
Thanks!

**Comment by tjallingt** [comment]
Did it not tag it correctly? I would have expected 7.10.1-canary.1 / 7.11.0-canary.1?

**Comment by ruisaraiva19** [comment]
We need to merge `master` into `canary` for `canary` to have the updated tags.

**Comment by ruisaraiva19** [comment]
@tjallingt  We did a mistake by merging the PRs to `master` with the `rebase and merge` option.

Going forward each PR to `canary`, we can use `squash and merge` and when merging from `canary` to `master`, we should do a simple merge to keep the same commit SHAs 😉.

By keeping the same commit SHAs, we automatically sync tags/versions across `master` and `canary`.

**Comment by tjallingt** [comment]
mhh will it then correctly generate the changelog? as every release will consist of a single commit?

**Comment by ruisaraiva19** [comment]
> mhh will it then correctly generate the changelog? as every release will consist of a single commit?

Each PR to `canary` should have only a single feature/fix and thus far a squash merge will do it.
When merging to `master`, we need a normal merge to keep all commit for a complete changelog.

**Comment by tjallingt** [comment]
I don't understand what I should do to make sure canary gets the updated tag?
This is my current understanding of how it should work:
```
| | * PR (feature branch)
| | |
| |/ <------ squash and merge
| * 1.0.0-canary.1 (pre-release branch)
| |\
| | |
| | * PR (feature branch)
| | |
| |/ <------ squash and merge
| * 1.0.0-canary.2 (pre-release branch)
| |
|/ <-------- rebase
* 1.0.0 (release branch)
|\ <-------- (?)
| |
| * (GOAL: equal with master, next PR merge will release x.x.x-canary.1)
```
Should a "correct" release also include some action at `(?)`, if so what action?
Or is there a mistake/missing step in my diagram?

**Comment by ruisaraiva19** [comment]
There is a mistake in your diagram. You have a rebase to release branch (1.0.0). From a pre-release branch (`canary`) to a stable branch (`master`) we should do a normal merge (no rebase 🙅‍♂️).

**Comment by tjallingt** [comment]
Ok so for clarity

```
| | * PR (feature branch)
| | |
| |/ <------ squash and merge
| * 1.0.0-canary.x (pre-release branch)
| |
|/ <-------- merge
* 1.0.0 (release branch)
|\ <-------- no action necessary here
| |
| * next PR merge will release x.x.x-canary.1
```

**Comment by ruisaraiva19** [comment]
Yes, that's correct.

**Pull request merged**
