### PR TITLE
docs(example): run example with Parcel

### PR DESCRIPTION
**Pull request by ruisaraiva19**
related to #218

Updates:
- example now runs with [Parcel](https://parceljs.org/) (`npm run example` or `yarn example`)
- example can now be built with `npm run example:build` or `yarn example:build`, this generates a `build` folder with static files that can be deployed to services like [Netlify](https://www.netlify.com/)

To-Do list:
- [x] migrate from [Webpack](https://webpack.js.org/) to [Parcel](https://parceljs.org/)
- [x] add build script for the example
- [x] deploy example to GitHub pages from `canary` branch

### CODE REVIEW

**Comment by ruisaraiva19** [comment]
@tjallingt Do you want to setup the project on [Netlify](https://www.netlify.com/) to deploy previews for each opened PR?

**Comment by tjallingt** [comment]
I figured we'd publish the master/canary branch to Netlify as well and stop using GitHub pages.
On the other hand GitHub pages comes with a nice url and you already setup the deploy workflow to automate it.

If we use GitHub pages for the home page (mirroring the current release/`master`) maybe we should use CodeSandbox CI instead for PR previews?
https://codesandbox.io/docs/ci

**Comment by ruisaraiva19** [comment]
> I figured we'd publish the master/canary branch to Netlify as well and stop using GitHub pages.
> On the other hand GitHub pages comes with a nice url and you already setup the deploy workflow to automate it.
> 
> If we use GitHub pages for the home page (mirroring the current release/`master`) maybe we should use CodeSandbox CI instead for PR previews?
> https://codesandbox.io/docs/ci

CodeSandbox CI sounds good. Later today I'll update Github pages to the `master` branch and add the CodeSandbox configuration needed!

**Comment by ruisaraiva19** [comment]
@tjallingt I added the CodeSandbox configuration file and updated the GitHub pages branch to `master`. 
You can now add the [CodeSandbox GitHub app ](https://github.com/apps/codesandbox)to start sandboxing 😉.

**Pull request merged**
