### PR TITLE
Re-scaffold with TSDX and add useYouTube hook

### PR DESCRIPTION
**Pull request by tjallingt**
This removes some maintenance on the Webpack config and gives us Typescript :tada:

Also added the base for a `useYouTube` hook, with the goal of rewriting the `<YouTube />` component using this hook while maintaining backwards compatibility.

Creating this PR to share progress (and maybe get some help?)

- [ ] Fix obviously simplistic hook implementation
- [ ] Remove dependency on `youtube-player`
- [ ] Update the `<YouTube />` component using the hook

This relates to the following issues:
#202 
#189

### CODE REVIEW

**Comment by tjallingt** [comment]
@ruisaraiva19 If you could take a look at this that would be amazing!

This is still very basic/untested so pretty far from a release but I hope we can achieve complete backwards compatibility

**Comment by ruisaraiva19** [comment]
@tjallingt yes, I'll take a look and continue with your todo list 👌.

**Comment by ruisaraiva19** [comment]
This will be on hold until #217 gets merged.

**Comment by tjallingt** [comment]
Closing as @ruisaraiva19 has done amazing work to update the projects tooling and TSDX is not the route we want to take right now. Will open a new PR for just the `useYouTube` hook (and the typescript-ification)

**Pull request closed without merging**
