### PR TITLE
Version 7.10.0

### PR DESCRIPTION
**Pull request by tjallingt**
feat: add semantic releases (#217)
feat: add Typescript definitions (#214)

The Typescript definitions are already in master (my mistake 🙊)

### CODE REVIEW

**Comment by ruisaraiva19** [comment]
@tjallingt We are having some issues with the `NPM_TOKEN` provided.

**Comment by ruisaraiva19** [comment]
Also, I need to update the release triggers.

**Comment by tjallingt** [comment]
Yea I have 2FA enabled and the NPM_TOKEN seems to require the code.
Not sure what the solution for that would be.

Also its trying to release the wrong version since the git tags where out of date.

**Comment by ruisaraiva19** [comment]
> Yea I have 2FA enabled and the NPM_TOKEN seems to require the code.
> Not sure what the solution for that would be.
> 
> Also its trying to release the wrong version since the git tags where out of date.

npm-token

**Comment by tjallingt** [comment]
Yep, dialed back the 2fa "level" on npm already

**Comment by tjallingt** [comment]
# 🎉 🎉 🎉 
https://github.com/tjallingt/react-youtube/releases/tag/v7.10.0-canary.1
https://www.npmjs.com/package/react-youtube/v/7.10.0-canary.1
https://www.runpkg.com/?react-youtube@7.10.0-canary.1/dist/index.js

**Comment by ruisaraiva19** [comment]
> # 🎉 🎉 🎉
> https://github.com/tjallingt/react-youtube/releases/tag/v7.10.0-canary.1
> https://www.npmjs.com/package/react-youtube/v/7.10.0-canary.1
> https://www.runpkg.com/?react-youtube@7.10.0-canary.1/dist/index.js

Looking good 🎉

**Comment by ruisaraiva19** [comment]
After this gets merged, changing the default branch to `canary` and removing the deprecated Travis CI build pipeline check will finish this migration to semantic releases 👌.

**Comment by tjallingt** [comment]
Canary as default is done!

I already removed Travis from the repo settings but seemingly that's not enough.
I unchecked this repo in Travis, I hope that makes the pipeline check in GitHub disappear.

**Comment by tjallingt** [comment]
@ruisaraiva19 the badges in the readme appear broken :( we should fix and/or remove them.
Is there a way to do that without triggering a new release?

**Comment by ruisaraiva19** [comment]
> @ruisaraiva19 the badges in the readme appear broken :( we should fix and/or remove them.
> Is there a way to do that without triggering a new release? (eg does only `chore` mean no new version gets published)

yes, `chore` doesn't trigger a new release.

**Comment by ruisaraiva19** [comment]
Badges updated here: #221

**Pull request merged**
