### PR TITLE
Make component compatible with styled-components providing the className for parent element

### PR DESCRIPTION
**Pull request by karolisgrinkevicius**
# Description
Make component compatible with [emotion](https://emotion.sh) and [styled-components](https://www.styled-components.com) providing the className for parent element.

# Motivation
Previously this component wasn't compatible neither with [emotion css in js](https://emotion.sh) nor [styled-components](https://www.styled-components.com) due to the class name being set for child element.

### CODE REVIEW

**Comment by ruisaraiva19** [comment]
@karolisgrinkevicius we have updated the codebase and this code is now outdated.
Can you please resolve the conflicts and update the tests as well?
Thanks.

**Comment by karolisgrinkevicius-home24** [comment]
@ruisaraiva19 I have rebased and fixed all the conflicts. Please take a look. Thanks.

**Comment by ruisaraiva19** [comment]
@karolisgrinkevicius-home24 we are using the `canary` branch as our default branch going forward. Can you please update this PR accordingly?

**Comment by karolisgrinkevicius** [comment]
@ruisaraiva19 thanks for the info, I have created another PR against `canary` origin branch here: https://github.com/tjallingt/react-youtube/pull/226 hence let's move the conversation directly in there.

**Pull request closed without merging**
