### PR TITLE
refactor to hooks and upgrade react version

### PR DESCRIPTION
**Pull request by zgabievi**
- Refactored to hooks
- Upgraded react version to latest
- Upgraded [shallow renderer](https://reactjs.org/docs/shallow-renderer.html) to newest version

---

Test are failing but everything is working in example. I think tests need to be rewritten, cause of hooks

### CODE REVIEW

**Comment by tjallingt** [comment]
Wow amazing, this is looking really nice 😍

Some of these errors look legit though so i'm not sure if the tests where wrong or there is some change in functionality because of the hooks... We will need to look into that.

Thoughts:
- This would be a major version bump because of the new dependency on react ^16.8.0
- Not sure what to do about the package-lock.json, i tend to use yarn myself and we already have a yarn.lock but i'm ambivalent to either tool 😕 
- For fixing the tests it might be nice to keep the _Youtube.js file around but we should fix the issue with the tests and get rid of the "old" implementation
- Eventually it might be nice if we can rewrite the tests with [react-testing-library](https://github.com/kentcdodds/react-testing-library) as a separate PR.

I just kinda noticed because of this PR (since i didn't look closely at this project for a while) we ought to typecheck the jsdoc comments with typescript and export a type definition file (shouldn't be much work).

**Comment by zgabievi** [comment]
Sure, tests could be failing because of new release, but should be checked. 
About package-lock.json: I'm using yarn too, but there are lots of developers who use npm and they should have package-lock too, in my opinion.
Yep, _YouTube should be deleted after all fixes.

I was thinking about TypeScript too, but it needs different boilerplate and it will be a little more work, but would be interesting. I will try to refactor tests, and rewrite project to TypeScript on my free time. For testing we can use Enzyme as shallow renderer

**Comment by tjallingt** [comment]
As for the typescript i'd prefer not to rewrite but just to fix our jsdoc comments to actually make sense to typescript see: https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript and adding `// @ts-check` at the top of Youtube.js

I believe maintaining both yarn.lock and package-lock.json is a bad idea, there are no guarantees they resolve to the same package versions and there is no way to "sync" them + that would be an extra maintenance burden. Not sure what the rest of the community (and npm and yarn devs) says about having both of them in one repo. The options as I see them are: remove both of them by adding them to gitignore or keep either of them (since everyone will have npm installed i guess package-lock.json makes the most sense to keep).

Again I'm not certain so i'd love to know what other projects do with lock files.

**Comment by capaj** [comment]
@zgabievi it virtually impossible to maintain two lockfiles side by side So yeah @tjallingt there should only be one lock file.

**Comment by tjallingt** [comment]
I really appreciate the work you put into this however I'm going to close this PR at this time.
I'm very interested in going with a different strategy; creating a `useYouTube` hook and a light wrapper component for backwards compatibility.
I hope you understand!

**Pull request closed without merging**
